### PR TITLE
Make the header stick to the top when scrolled

### PR DESCRIPTION
**Pull request by LukasPietzschmann**

### CODE REVIEW

**Comment by Tanikai** [comment]
Looks great on desktop, but I think that the sticky header makes the UI on small screens a bit cluttered / cramped (screenshot with iPhone SE 2nd gen size):

image

Off the top of my head, there are multiple approaches:
- Hide the header when scrolling down, and show it again (sticky) when scrolling up a defined amount of vertical space
- Reduce the header height (might be a bit difficult due to the day and canteen selection)

**Comment by LukasPietzschmann** [comment]
Yeah, you're right!

I like the first idea. That also what search engines often do (at least DuckDuckGo :D). I'll implement it tomorrow. Thanks for your feedback :)

**Comment by LukasPietzschmann** [comment]
Alright, I implemented what you suggested. But I think it's a bit unnecessary on desktop, so I would probably guard it behind a media query. What do you think about that?

**Comment by Tanikai** [comment]
Yes, I would only hide the header on small screens. On Tablets / Desktops, there should be enough space for the meals.

**Comment by LukasPietzschmann** [comment]
Done :)

**Pull request merged**
